projects:
  portfolio:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: wy5pvg4wwjd2dfapw2a5ta4iue
      endpoints:
        prod: >-
          https://2vh443akl5e5dgh6dbcv3jv7mq.appsync-api.us-east-1.amazonaws.com/graphql
