// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://2vh443akl5e5dgh6dbcv3jv7mq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kralpfpdqbh6nafblsrkdiwsnu",
    "aws_content_delivery_bucket": "portfolio-1-20190208163455-hostingbucket-portfolio",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://portfolio-1-20190208163455-hostingbucket-portfolio.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
